# Generated by Django 4.1.12 on 2023-11-22 06:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horastomadas',
            name='fecha',
            field=models.DateTimeField(default=datetime.timezone),
        ),
        migrations.AddField(
            model_name='horastomadas',
            name='servicio',
            field=models.ForeignKey(default='otro', on_delete=django.db.models.deletion.CASCADE, to='core.servicio'),
        ),
        migrations.AddField(
            model_name='horastomadas',
            name='vehiculo',
            field=models.CharField(default='null', max_length=40),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='id_servicio',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
