# Generated by Django 4.1.12 on 2023-11-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_horastomadas_fecha_horastomadas_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horastomadas',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
